
#################################
#
#  NOTE: Do not edit this file.
#

import sys

from nqueens import solve

if len(sys.argv) != 2:
    print("\n\tUsage: python3 run.py <test-file>\n")
    exit(1)

in_file = sys.argv[1]

problems = []

with open(in_file) as f:
    problems = map(int, f.readlines())

for p in problems:
    print(solve(p))

